name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - backend/docs/**/*
      - .github/workflows/deploy-to-github-pages.yml

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/docs
    steps:
      - uses: actions/checkout@v2

      - name: Install swagger-cli
        run: |
          npm install -g swagger-cli

      - name: Validate Swagger Files
        run: |
          swagger-cli validate -d openapi.yaml --type yaml

      - name: Generate Swagger UI
        if: github.event.pull_request.merged == true
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: openapi.yaml

      - name: Deploy to GitHub Pages
        if: github.event.pull_request.merged == true
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_KEY }}
          publish_dir: swagger-ui
