name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - backend/docs/**/*
      - .github/workflows/deploy-to-github-pages.yml

defaults:
  run:
    working-directory: backend

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install swagger-cli
        run: |
          npm install -g swagger-cli

      - name: Validate Swagger Files
        run: |
          swagger-cli validate -d docs/openapi.yaml --type yaml
      - name: debug
        run: ls
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: docs
          spec-file: docs/openapi.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
