name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - backend/docs/**/*
      - .github/workflows/deploy-to-github-pages.yml
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          npm install -g swagger-cli swagger-parser yamljs

      - name: Generate Swagger Files
        run: node main.js
      - name: Validate Swagger Files
        run: |
          swagger-cli validate -d backend/docs/openapi.yaml --type yaml
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: backend/docs/dest/.
          spec-file: backend/docs/openapi.yaml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: backend/docs/dest/**/*
