# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      mysql:
        image: mysql:9
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: password
          TZ: "Asia/Tokyo"
    env:
      RAILS_ENV: test
      DATABASE_URL: "mysql://root:password@localhost:3306/kintai_test"
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: "mysql://root:password@localhost:3306/kintai_test"
      DB_DATABASE: kintai_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
        with:
          bundler-cache: true
          ruby-version: '3.1.6'
      # Bundle install
      - name: Bundle install
        run: bundle install
      # Add or replace database setup steps here
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start
      - name: Set up database schema
        run: bin/rails db:migrate
      # Add or replace test runners here
      - name: Run tests
        run: bin/rails test
