# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      mysql:
        image: mysql:9
        env:
          MYSQL_DATABASE: kintai_test
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: '%'
          TZ: "Asia/Tokyo"
    env:
      RAILS_ENV: test
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: localhost
      DB_DATABASE: kintai_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@540484a3c0f308b08619664ec40bf6c371d172c3 # v1.205.0
        with:
          bundler-cache: true
          ruby-version: '3.1.6'
      # Bundle install
      - name: Bundle install
        run: bundle install
      # Add or replace database setup steps here
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start
      - name: Set up database schema
        run: bin/rails db:create RAILS_ENV=test
      - name: Set up database schema
        run: bin/rails db:migrate RAILS_ENV=test
      # Add or replace test runners here
      - name: Run tests
        run: bin/rails test
